### ISSUE TITLE
This plugin has some problem in QGIS 3.24 

### ISSUE THREAD

**Issue by matself** [biglimp/qgis-fusion#11]
In 3.22.1 all is well, but in 3.24 Tisler, the plugin fails on load.

Couldn't load plugin 'processing_fusion' due to an error when calling its classFactory() method 

```
ModuleNotFoundError: No module named 'processing.core.ProcessingLog' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_fusion\__init__.py", line 35, in classFactory
    from .processing_fusion import ProcessingFUSIONPlugin
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_fusion\processing_fusion.py", line 36, in 
    from .processing_fusion_provider import ProcessingFUSIONProvider
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_fusion\processing_fusion_provider.py", line 35, in 
    from processing_fusion.algs.ascii2dtm import ascii2dtm
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_fusion\algs\ascii2dtm.py", line 39, in 
    from processing_fusion.fusionAlgorithm import FusionAlgorithm
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_fusion\fusionAlgorithm.py", line 35, in 
    from processing_fusion import fusionUtils
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_fusion\fusionUtils.py", line 36, in 
    from processing.core.ProcessingLog import ProcessingLog
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing.core.ProcessingLog'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.0-Tisler Tisler, 6b44a42058 

```
```
Python Path:
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.24.0\bin
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by biglimp** [comment]
It looks like ProcessingLog is deprecated. I had a look in the code and it is actually not used so It is just to comment line 36 in fusionUtils.py and reload the plugin. I will submit an updated version to the QGIS repo asap.

**Comment by biglimp** [comment]
Problem solved.

**Comment by matself** [comment]
Thanks for a speedy response! I can confirm that the plugin loads without trouble after commenting out the failing line.
